spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:user-service-local}

  data:
    redis:
      host: ${APP_REDIS_HOST:localhost}
      port: ${APP_REDIS_PORT:6379}
      password: ${APP_REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      connect-timeout: 30000

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/routexhub}
    username: ${SPRING_DATASOURCE_USERNAME:routex}
    password: ${SPRING_DATASOURCE_PASSWORD:routex@2026}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

identity:
  jwt:
    secret: ${JWT_SECRET:local-jwt-secret}