spring:
  application:
    name: go-routex-user-service

  threads:
    virtual:
      enabled: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "vn.com.*"
        
    events:
      ticket-issued: "routex.ticket.issued"
      notification-email: "routex.notification.email"

    topics:
      booking: "route.bookings.event"

    group-id:
      membership: "user-service-membership"

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      sort-properties-alphabetically: false

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:admin}

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:6MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:6MB}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: ${SERVER_PORT:8081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}
  client:
    merchantService:
      address: ${MERCHANT_SERVICE_GRPC_ADDRESS:static://localhost:9090}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

client:
  verify:
    url: ${CLIENT_URL:http://localhost:8080/}

identity:
  jwt:
    secret: ${JWT_SECRET:CZZRadv0Xe8z3stWFWYdtiJ2E86gUgJvFEfbCYFgJhQ}
    access-token-expiration-minutes: 60
    refresh-token-expiration-days: 7
    issuer: ${JWT_ISSUER:user-service}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.transaction: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN