spring:
  config:
    activate:
      on-profile: dev

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:kafka:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:user-service}

  data:
    redis:
      host: ${APP_REDIS_HOST:redis}
      port: ${APP_REDIS_PORT:6379}
      password: ${APP_REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      connect-timeout: 30000

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/routex}
    username: ${SPRING_DATASOURCE_USERNAME:routex}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}