spring:
  application:
    name: go-routex-user-service

  threads:
    virtual:
      enabled: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "vn.com.*"

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      sort-properties-alphabetically: false

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:admin}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

jms:
  thread:
    receive:
      timeout-seconds: ${JMS_THREAD_RECEIVE_TIMEOUT_SECONDS:30}
    send:
      timeout-seconds: ${JMS_THREAD_SEND_TIMEOUT_SECONDS:5}
  receive:
    timeout: ${JMS_RECEIVE_TIMEOUT:30000}
  caching:
    session-cache-size: ${JMS_CACHING_SESSION_CACHE_SIZE:256}
  time-to-live-milliseconds: ${JMS_TIME_TO_LIVE_MILLISECONDS:20000}
  recovery-interval: ${JMS_RECOVERY_INTERVAL:5000}
  max-message: ${JMS_MAX_MESSAGE:1}

server:
  port: ${SERVER_PORT:8080}

client:
  verify:
    url: ${CLIENT_URL:http://localhost:8080/}

identity:
  jwt:
    secret: ${JWT_SECRET:CZZRadv0Xe8z3stWFWYdtiJ2E86gUgJvFEfbCYFgJhQ}
    access-token-expiration-minutes: 60
    refresh-token-expiration-days: 7
    issuer: ${JWT_ISSUER:user-service}

notification:
  email:
    provider: sendgrid
    sendgrid:
      baseUrl: ${BASE_URL:http://localhost:8000/}
      api-key: ${SENDGRID_API_KEY}
      from-email: ${SENDGRID_FROM_EMAIL:simon@routex-go.com}
      from-name: ${SENDGRID_FROM_NAME:Go-Routex}
      verify-subject: ${SENDGRID_VERIFY_SUBJECT:Registration Form - Verify your Email}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN